application: webminingapp
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
  
- url: /redir_url.*
  script: webminingapp.app2
  
- url: /sign.*
  script: webminingapp.app1
  
- url: /.*
  script: webminingapp.app1
  
libraries:
- name: lxml
  version: "latest"